archetypeDir:               "archetypes"

# hostname (and path) to the root, e.g. http://spf13.com/
baseURL:                    "/"

# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# include content already expired
buildExpired:               false

# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               true

# config file (default is path/config.yaml|json|toml)
config:                     "config.yaml"
contentDir:                 "content"
dataDir:                    "data"
defaultExtension:           "html"
defaultLayout:              "post"

# Missing translations will default to this content language
defaultContentLanguage:     "en"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: false

# The below example will disable all page types and will render nothing.
disableKinds: [ "taxonomy", "taxonomyTerm", "RSS", "sitemap" ]
disableLiveReload:          false
# Do not build RSS files
disableRSS:                 true
# Do not build Sitemap file
disableSitemap:             true
# Enable GitInfo feature
enableGitInfo:              false
# Build robots.txt file
enableRobotsTXT:            true
# Do not render 404 page
disable404:                 false
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: false

# edit new content with this editor, if provided
editor:                     "subl"

# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji:                false

# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders: true

footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""

# google analytics tracking id
googleAnalytics:            ""

languageCode:               "en"

layoutDir:                  "layouts"

# Enable Logging
log:                        false
# Log File path (if set, logging enabled automatically)
logFile:                    ""

# "yaml", "toml", "json"
metaDataFormat:             "yaml"

newContentEditor:           "subl"

# Don't sync permission mode of files
noChmod:                    false
# Don't sync modification time of files
noTimes:                    false

paginate:                   10
paginatePath:               "page"

permalinks:
# Pluralize titles in lists using inflect
pluralizeListTitles:        true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames:      false

# filesystem path to write files to
publishDir:                 "public"

# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax: false
# color-codes for highlighting derived from this style
pygmentsStyle:              "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses:         false

# maximum number of items in the RSS feed
rssLimit:                   15

SectionPagesMenu: "main"

# default sitemap configuration map
sitemap:

# filesystem path to read files relative from
source:                     ""
staticDir:                  "static"

# display memory and timing of different steps of the program
stepAnalysis:               false

# theme to use (located by default in /themes/THEMENAME/)
themesDir:                  "themes"
theme:                      ""

title:                      ""

# if true, use /filename.html instead of /filename/
uglyURLs:                   false
# Do not make the url/path to lowercase
disablePathToLower:         false

# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage:             false

# verbose output
verbose:                    true
# verbose logging
verboseLog:                 false
# watch filesystem for changes and recreate as needed
watch:                      false