// Standard lib.
import {
  extname,
  resolve
} from 'path';

// Package modules.
import stylelintPlugin from '@amatlash/vite-plugin-stylelint';
import globby from 'globby';
import { minify } from 'html-minifier-terser';
import eslintPlugin from 'vite-plugin-eslint';

// Local modules.
import { config } from './package.json';

// Constants.
const INPUT_DIRECTORY = resolve(__dirname, config.input);
const INTERMEDIATE_DIRECTORY = resolve(__dirname, config.intermediate);
const OUTPUT_DIRECTORY = resolve(__dirname, config.output);

// Runtime constants.
const PRODUCTION = process.env.NODE_ENV === 'production';

// Output map.
const ASSET_MAP = {
  css: 'styles'
};

// Helpers.
function getEntryPoints(dir) {
  return globby('*', {
    absolute: true,
    baseNameMatch: true,
    cwd: dir,
    onlyFiles: true
  });
}

// Plugins.
const htmlMinifyPlugin = (opts) => ({
  name: 'html-minifier-terser',
  enforce: 'post',

  transformIndexHtml(html) {
    return PRODUCTION ? minify(html, opts) : html;
  }
});

// Exports.
module.exports = async () => {
  const files = await getEntryPoints(INTERMEDIATE_DIRECTORY);

  return {
    assetsInclude: ['**/*.txt'],
    publicDir: resolve(__dirname, 'public/'),
    root: INTERMEDIATE_DIRECTORY,

    build: {
      assetsDir: 'scripts',
      outDir: OUTPUT_DIRECTORY,
      rollupOptions: {
        input: files,
        output: {
          assetFileNames({ name }) {
            if (name.includes('node_modules/')) {
              return 'vendor/[name].[hash][extname]';
            }
            const dir = ASSET_MAP[extname(name).substr(1)] ?? 'assets';
            return `${dir}/[name].[hash][extname]`;
          }
        }
      }
    },
    plugins: [
      eslintPlugin(),
      stylelintPlugin(),
      htmlMinifyPlugin({
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        conservativeCollapse: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        maxLineLength: 120,
        minifyCSS: true,
        minifyJS: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        useShortDoctype: true
      })
    ],
    resolve: {
      alias: {
        '/src': INPUT_DIRECTORY,
        '/~': resolve(__dirname, 'node_modules/')
      }
    }
  };
};
