# https://gohugo.io/getting-started/configuration/
baseURL = ""
buildDrafts = true
buildExpired = true
buildFuture = true
enableMissingTranslationPlaceholders = true
log = true
newContentEditor = "subl"
relativeURLs = true
verboseLog = true
